name: Deploy Documentation to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Build Documentation
        run: pip install -r requirements.txt 
        run: mkdocs build --strict --verbose
      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: site

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build joint-js-evaluation
        run: |
          cd joint-js-evaluation
          npm install
          npm run build
      - name: Deploy joint-js-evaluation
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: joint-js-evaluation/dist
          target-folder: joint-js-evaluation

      - name: Install and Build diagram-js-evaluation
        run: |
          cd diagram-js-evaluation
          npm install
          npm run build
      - name: Deploy diagram-js-evaluation
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: diagram-js-evaluation/dist
          target-folder: diagram-js-evaluation